### ISSUE TITLE
Silly questions

### ISSUE THREAD

**Issue by JokerQyou** [paradite/retire-at-35#2]
So basically the word "retirement" used in the README means "planned financial independence", is that correct? If one choose to keep working (for whatever reason) even if he / she is financial independent, does that count as a form of retirement?

**Comment by paradite** [comment]
Good question. Indeed "retirement" here is being slightly redefined by me here. You can still work after retirement as long as you are not dependent on the income generated from working. In fact I encourage "working" on your passion or interest.

**Comment by JokerQyou** [comment]
Thanks for the inspiration!
