### ISSUE TITLE
You can actually retire at 27

### ISSUE THREAD

**Issue by chao1995** [paradite/retire-at-35#3]
If you go to TIananmen Square and sing the song 人民不需要自由。

**Comment by chao1995** [comment]
谁都没有想到，有一天，会因为一场火灾，让他们团结起来，走到街上，给上面的人知道，能被愚昧统治的人，最不配当中国人。

https://www.youtube.com/watch?v=rQsEQgltycg

**Comment by paradite** [comment]
Please stop posting irrelevant information in this repo. If you don't stop, I will have to block you.

**Comment by chao1995** [comment]
Please block me. :)
