### ISSUE TITLE
Is indie hacking really better than a tech job for a youngster to retire at 35?

### ISSUE THREAD

**Issue by chao1995** [paradite/retire-at-35#6]
Hi Zhu Liang! I have a quite personal question for you, as per title, but you can choose not to answer.

I am wondering what propels you to resign from your job at Ant and start indie hacking/game dev? Has your side projects provide you a similar level of (or a steady stream of) income when you quitted? Would love to know your thought process here, since I believe you have done the calculation especially knowing that you have "retiring at 35" in mind, too. (Sorry that if you have written a blogpost/tweet on this but I missed it, please point me to them, thank you!)

**Comment by paradite** [comment]
Thanks. I will maybe write a blogpost on this to explain my thought process when I have free time.

But closing this since it is off-topic.
