### ISSUE TITLE
Why FIRE doesn't work, according to an ex-Google, ex-Facebook millionaire.

### ISSUE THREAD

**Issue by chao1995** [paradite/retire-at-35#7]
https://www.youtube.com/watch?v=k2wbW5SwgDM&ab_channel=TechLead

**Comment by paradite** [comment]
please stop opening issues for such content, it is not what issues are for.

**Comment by chao1995** [comment]
C'mon, it's TechLead. Not your average tech lead. He is ex-Google, ex-Facebook TechLead, `the TechLead`.
